// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs0_mX-QXj_jgzIzUqN8Z9fKCuZH225jU',
    appId: '1:233326359871:web:7d80eced60be75938d8f8a',
    messagingSenderId: '233326359871',
    projectId: 'realtime-67b18',
    authDomain: 'realtime-67b18.firebaseapp.com',
    storageBucket: 'realtime-67b18.appspot.com',
    measurementId: 'G-7EP7MMNHQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsX3wLjHDvt7cWSaWbMCWgBQTEg4lgPVQ',
    appId: '1:233326359871:android:692026d15d618a848d8f8a',
    messagingSenderId: '233326359871',
    projectId: 'realtime-67b18',
    storageBucket: 'realtime-67b18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhunSv7hClPGZxBNzGqdXCMYokw_SudkU',
    appId: '1:233326359871:ios:5322a459a88c36218d8f8a',
    messagingSenderId: '233326359871',
    projectId: 'realtime-67b18',
    storageBucket: 'realtime-67b18.appspot.com',
    iosBundleId: 'com.example.esaviorDriverProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhunSv7hClPGZxBNzGqdXCMYokw_SudkU',
    appId: '1:233326359871:ios:5322a459a88c36218d8f8a',
    messagingSenderId: '233326359871',
    projectId: 'realtime-67b18',
    storageBucket: 'realtime-67b18.appspot.com',
    iosBundleId: 'com.example.esaviorDriverProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs0_mX-QXj_jgzIzUqN8Z9fKCuZH225jU',
    appId: '1:233326359871:web:9bba7302f761cb0f8d8f8a',
    messagingSenderId: '233326359871',
    projectId: 'realtime-67b18',
    authDomain: 'realtime-67b18.firebaseapp.com',
    storageBucket: 'realtime-67b18.appspot.com',
    measurementId: 'G-10L8C56RV5',
  );
}
